### ISSUE TITLE
Quit messages aren't displayed at all

### ISSUE THREAD

**Issue by wasamasa** [jorgenschaefer/circe#155]
I didn't notice this at first because I did customize `circe-reduce-lurker-spam`, but then found out that even quits from recently active entities weren't displayed at all.

**Comment by jorgenschaefer** [comment]
Indeed, thanks for the report. Likewise, the message "joined xyz minutes ago" is not displayed all the time, leading me to assume that the bridge to the new last activity times is broken.

**Comment by jorgenschaefer** [comment]
The problem is that `circe-user-channels` does not know which channels this user was on, as they have been removed by the time the display function is called.

The correct solution to this would be to emit a separate "user quite channel" event and display that.

(It's a general problem for IRC if you want to display events separate from when you handle them, but you want to have that separation for abstraction reasons. Meh.)
