### ISSUE TITLE
Any way to namespace the channel names?

### ISSUE THREAD

**Issue by bradens** [jorgenschaefer/circe#218]
Hey, love the project!

I'm currently using it with slack, but the problem is that I have quite a few slack teams, and i want to log into them all at once.  

The problem is that when i do, i get a buffer for each channel (it auto-joins them all, regardless of what i put in the `channels` option (probably because they all need to be tracked?).  Anyways, each slack team has a general channel and right now they end up being named `#general`, then `#general<2>`, and there is no way for me to differentiate. 

Any way to change the way the channels are named?

**Comment by wasamasa** [comment]
Emacs offers [Uniquify](https://www.gnu.org/software/emacs/manual/html_node/emacs/Uniquify.html) for this, unfortunately it won't work because the buffers aren't associated with files, so you can't use directories for disambiguation.

If Slack's IRC gateway is anything like ZNC, autojoin settings have to be set up there, not in Circe.  Do you know of any way to find out which channel belongs to which team?

**Comment by jorgenschaefer** [comment]
Currently, I'm afraid the only option you have is to use the `circe-channel-mode-hook` and `rename-buffer` to change the names to whatever you like when the buffer is created. Circe uses buffer objects, not names, to track them, so you can rename to whatever you like.

I think it would be good for Circe to offer a `circe-channel-buffer-name` variable like the already existing `circe-server-buffer-name`.

**Comment by bradens** [comment]
Hmmm ok. Thanks guys.  I'll rename them with that hook for now, but @jorgenschaefer having a variable like that to customize would be great.

**Comment by jorgenschaefer** [comment]
@bradens, `(with-circe-server-buffer circe-server-name)` should get you the server name and `(with-circe-server-buffer circe-server-network)` the network name you specified in your config. :-)

**Comment by bradens** [comment]
Thanks! Works great.
