### ISSUE TITLE
Duplicated "Freenode" entry after customization

### ISSUE THREAD

**Issue by brabalan** [jorgenschaefer/circe#220]
Following, the manual, I added the following to my init file:
``` emacs-lisp
(setq circe-network-options
      '(("Freenode"
         :nick "brab"
         :nickserv-password "****"
         :channels ("#emacs-circe")
         )
        ("Elvum"
         :use-tls t
         ...)))))
```

When I start circe, I now see two instances of Freenode that I can choose from:
![screen shot 2015-09-17 at 09 45 34](https://cloud.githubusercontent.com/assets/1021637/9927678/e78b7d8c-5d20-11e5-8794-64707d866f12.png)

Is there a way to have only one of them?

**Comment by jorgenschaefer** [comment]
Interesting! What completion framework are you using there? That's not the default Emacs one.

The problem is that `circe--read-network-and-options` does not de-duplicate the completion candidates. The default Emacs completion does not propose the same option twice, but whatever you are using there does.

Circe should de-duplicate the list, just to avoid such issues, though.

**Comment by brabalan** [comment]
I’m using ivy-mode (part of swiper, https://github.com/abo-abo/swiper).
