### ISSUE TITLE
Could lui allow a specific time stamp to be specified?

### ISSUE THREAD

**Issue by ryuslash** [jorgenschaefer/circe#236]
Hi,

As I've mentioned in issue #235, I'm working on using `lui-mode` in another project. This project contains some messages that are part of a conversation's history, and thus have been sent (and possibly received) in the past. Each incoming message has a timestamp, so we could use that if we had the ability to specify a timestamp to use, instead of always using the current time in `lui-time-stamp`.

So far I've thought of two ways to do this, and I would like to know your opinion which would be preferred, if any, or if you have a better idea. 

1. We could add an optional argument to both `lui-time-stamp` and `lui-insert`, so we could specify for each message inserted with `lui-insert` what its time stamp would be. This seems fairly clean to me as the api to `lui-insert` would change in a rather non-invasive way, as would that of `lui-time-stamp`.

2. We could add a special (or dynamic) variable which should usually be nil, which we could let-bind when we need to change the timestamp for a certain message. This seems somewhat more obscure to me, but doesn't change the api of either `lui-insert` nor `lui-time-stamp`. It might also signal to users of the api (me, in this case) that this isn't really something you'd want to do unless absolutely necessary, if that is the case.

If you're open to this I would gladly send in a patch to do this, or any other option which has your preference.

I look forward to reading your response. Thanks in advance for your time.

Cheers,

Tom

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the suggestion!
Someone recently also asked for a way of setting the `ZONE` argument to `format-time-string`, so that's two requests for the same piece of code.

Changing the time there is a bit tricky, as it is easy to confuse the user and lui when displaying time stamps that do not follow normal expectations of time (i.e. monotonic increase).

I can see three possibly ways of doing this:

1. Provide global, dynamic variables that can be let-bound for both `TIME` and `ZONE` in `lui-time-stamp`. Solves the current problems pretty cleanly.
2. Provide our own `lui-format-time-string` function which can be overridden by lui clients to do all sorts of magic. More extensible, but less easy to use.
3. Use a text property in the strings to be displayed that detail the time stamp. Very nice interface for the lui client (can tag messages with their time stamps), but makes it very easy for the programmer to make mistakes with time ordering.

The easiest way that solves the current problems is probably (1), so I'd lean towards that, unless someone has particular preferences towards (2) or (3)?

**Comment by ryuslash** [comment]
Hi,

Thanks for your reply.

Actually, that's why I'm asking for this, because currently when I open a conversation in this project I'm working on I will get messages from yesterday with the time stamp of the moment I open the conversation. Also because the central service that we're working with is leading in just about everything and sends the timestamp of each message along with the message, it is technically more accurate to go by the timestamp sent to us by the service rather than the timestamp Emacs gets the message.

I think 1 has my preference also. It's basically my 2nd suggestion, except with zone included as well.

Although I do think that 2 is probably more extensible, but we'd have to either change the `lui-time-stamp` and `lui-insert` calling signatures or I'd have to use something like `cl-letf` to define my formatting function since I get the timestamp along with the message and I don't see any other way to pass that information along to the theoretical `lui-format-time-string`.

I'll try and write this up tonight, or as soon as I find some time, if you don't beat me to it :)

**Comment by jorgenschaefer** [comment]
Thank you!

**Comment by jorgenschaefer** [comment]
I suspect this is done, actually. Thank you again!

**Comment by ryuslash** [comment]
Yes indeed, sorry.
