### ISSUE TITLE
Swiper breaks colors

### ISSUE THREAD

**Issue by mekeor** [jorgenschaefer/circe#303]
When I run [`swiper`](https://github.com/abo-abo/swiper) command within a circe-buffer, all colors are gone. A friendly person called `alphor` from `#emacs-circe` IRC channel suggested me to add the following function to `circe-mode-hook` in order to solve this issue which indeed works:

```
(add-hook 'circe-mode-hook (lambda () (setq-local font-lock-ensure-function 'ignore)))
```

What causes this issue?

**Comment by wasamasa** [comment]
Looks like https://github.com/abo-abo/swiper/blob/master/swiper.el#L224-L273

As for why Swiper is doing that, I guess for making sure search candidates show up highlighted.  Enabling font-lock in Circe discards all previously present colors, so that's probably what's going on.  Have you considered opening a bug for swiper to add Circe to the list of excluded modes?

**Comment by mekeor** [comment]
That's a good idea, @wasamasa. Thank you. I'll report a bug. I think I could close this issue then.
